---
title: "ASSIGNMENT 4"
author: "RUTHRESHWARAN"
date: "2023-04-03"
output:
  html_document: default
  pdf_document: default
---


```{r}
library(ggplot2)
library(haven)
datatibble1<- read_sav("Raw/chap6data.sav")
datatibble1
datatibble1$owner

datatibble1$rerelate

```

- Calculate Descriptive Statistics & Visualize

Independent Variable: Owner

```{r}
freq_table <- table(datatibble1$owner)
freq_table

prop.table(freq_table)

summary(datatibble1$owner)
library(psych)
describe(datatibble1$owner)


label1 <- c("publically listed","privately owned","trust / charity","public sector")

pie(freq_table, label1, main="Pie Chart: owners",col = rainbow(length(freq_table)))
```

Dependent Variable: rerelate

```{r}
freq_table1 <- table(datatibble1$rerelate)
freq_table1

summary(datatibble1$rerelate)
describe(datatibble1$rerelate)
hist(datatibble1$rerelate, breaks = 5)
```


One-Way ANOVA:

```{r}

org_aov <- aov(datatibble1$rerelate ~ factor(datatibble1$owner))

org_aov

summary(org_aov)

library(car)

leveneTest(datatibble1$rerelate ~ factor(datatibble1$owner),centre = mean)


```

Effect Size:

```{r}

library(sjstats)

effectsize::eta_squared(org_aov, partial = TRUE)

```

```{r}
library(effectsize)

Aov <- oneway.test(owner ~ rerelate, data = datatibble1, var.equal = TRUE)
effectsize(Aov)
effectsize(org_aov)
effectsize(org_aov, partial = TRUE)
effectsize(org_aov, partial = FALSE)


```

```{r}
library(afex)
eta_squared(org_aov)

omega_squared(org_aov)


```

Post-hoc Test:

```{r}
TukeyHSD(org_aov)


```

Exploring the variable "Variety":

```{r}
summary(datatibble1$cvariety)
describe(datatibble1$cvariety)
freq_table1 <- table(datatibble1$cvariety)
freq_table1
cumsum(freq_table1)
prop.table(freq_table1)

hist(datatibble1$cvariety)
```

```{r}
org_aov1 <-aov(cvariety ~ factor(owner), data = datatibble1)

summary(org_aov1)

leveneTest(cvariety ~ factor(owner), data = datatibble1, centre = mean)

```

```{r}

eta_squared(org_aov1)

omega_squared(org_aov1)



```

Post-hoc Test:

```{r}
library(dplyr)
library(ggplot2)

result <- TukeyHSD(org_aov1)
df <- as.data.frame(datatibble1)



```






```






